#!/bin/bash

if ! grep 'precommit = python setup.py all' .hg/hgrc > /dev/null 2>&1
then
    echo "Installing pre-commit hooks into .hg/hgrc"
    echo >> .hg/hgrc
    echo '[hooks]' >> .hg/hgrc
    echo 'precommit = python setup.py all' >> .hg/hgrc
fi
