#!/bin/bash

STATUS=0
for SOURCE in *.py $(find tgutils -name '*.py') $(find tests -name '*.py')
do
    autopep8 -a -a -a -a --max-line-length 100 - < ${SOURCE} > .reformat
    isort -ds -dt -fas -q -sl -w 100 -p tgutils .reformat > /dev/null
    if ! cmp -s ${SOURCE} .reformat
    then
        echo "### ${SOURCE}"
        diff ${SOURCE} .reformat
        STATUS=1
    fi
    if grep -Hn "[^=][^][\"'a-zA-Z0-9_,:)#}{.?!\\=\`]$" ${SOURCE} \
     | grep -v -- '--$' \
     | grep -v 'from \(pandas\|numpy\) import \*$'
    then
        STATUS=1
    fi
done

rm -rf .reformat
exit $STATUS
