#!/bin/bash

set -e

cd ..
rm -rf sphinx/*.rst sphinx/generated html
mkdir -p sphinx/static sphinx/templates sphinx/themes sphinx/resources
cp *.rst docs/*.rst sphinx
sphinx-apidoc -f -o sphinx tgutils
