#!/bin/bash

set -e

cd ..
test -f dynamake/version.py || python setup.py --help > /dev/null
rm -rf sphinx/*.rst sphinx/generated html
mkdir -p sphinx/static sphinx/templates sphinx/themes sphinx/resources
cp *.rst docs/*.rst sphinx
sphinx-apidoc -f -o sphinx tgutils
